### ISSUE TITLE
magicblast question

### ISSUE THREAD

**Issue by lfaino** [bioinformagic/monica#3]
Hi @simozhou,
i used a bit Magicblast and i saw i strange behavior. if i make a custom database, after the mapping, i loose the information of the subject to which the query match to...

can you please have a look?

Cheers
Luigi

**Comment by simozhou** [comment]
Are you referring to a loss of information within the database (you don't know which sequence maps to which organism) or to the query sequences (can't find the read ID)?

Can you please attach some lines of your sam output?

Output sams usually have both sequence id (from the fastq read) and reference id (the one on the fasta of the blastdb).

What is missing there?

**Comment by lfaino** [comment]
If I run magicblast -db Pantoea.all.fasta -query flappie/barcode01.fastq  -infmt fastq -outfmt tabular | grep -v "#" | head using the custom database "Pantoea.all.fasta"
i get the following output:
943f1d51-fd23-40eb-8ddc-f56d430b3514    64      95.1368 0       0       0       195     518     84471   84795   0       99      249     plus    plus    617     19ATCG21-T26G-2AGGA18-G13GA-A12AG3A-G-8AG1A-75-A88-C27    3       -       1:0     GTAGGAGTTCGCGGTGATCATCTTCCTGCA  TGGGGCGTCGTGGTCGTTGCAGGCGACAGA  -       -       249
9

where 64 is the name of the subject but it is an arbitrary number not the name of the matching subject from the original fasta file.

Cheers
Luigi

**Comment by simozhou** [comment]
have you built the database using the flag `-parse_seqids`? The problem to me seems to be related to the `makeblastdb` command rather than magicblast itself

**Comment by lfaino** [comment]
ok. it works.

thanks
