### ISSUE TITLE
I got a GPU nvidia card

### ISSUE THREAD

**Issue by lfaino** [bioinformagic/monica#4]
Hi @ioneliabuzatu and all,
i got a GPU card Nvidia GTX 1070. I hope we can use for this project as well.

Cheers
Luigi

**Comment by jaydee220** [comment]
Good news! planning to use deepbinner over GPU only so that the cpu can take care of the other processes.

**Comment by simozhou** [comment]
@ioneliabuzatu can you please take care of setting up a gpu-feasible tensorflow library within the docker image please?

Referencing this issue within the `class main board` project

**Comment by ghost** [comment]
That's exciting news! Yes, I will update the docker file this weekend.
