### ISSUE TITLE
reconsidering using metaphlan2

### ISSUE THREAD

**Issue by lfaino** [bioinformagic/monica#9]
Hi @simozhou,
i had a look at the metaphlan2 software and it may work but we need to seat together and see how to make some modifications. the nice of the tool is the output (it can be parsed by the code in the other issue directly). however, we need to change the mapper to allow long reads to be mapped with an higher speed. 

let`s talk on tuesday

Cheers
Luigi

**Comment by simozhou** [comment]
by changing the mapper what we do is basically transforming metaphlan2 in magic-blast with a smaller database (100 species of fungi for metaphlan while our has all species from refseq...). Plus the output with `bammer.py` is very close to metaphlan2's output (sampleID - referenceID). As of now, it doesn't seem necessary, but we can discuss that on tuesday.
